# This is a gated build to verify the validity of the code

name: Gated-Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        
          
